version: '3'

services:
  database-frontend:
    build: database-frontend/
    depends_on:
      - 'database-project'
    ports: 
      - '3000:3000'
    stdin_open: true

  database-project:
    build: database-project/
    depends_on:
      - 'postgres'
    ports:
      - '3001:3001'
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql